### ISSUE TITLE
cant flash on poker2 with backlight

### ISSUE THREAD

**Issue by gompa** [lactide/tmk_nuvoton#2]
if you build the current code and flash it on a poker with backlight you brick the board 

you can fix it by setting dipswitch 4 to active while plugging the board in and disabling the switch after it booted (the tab/caps button wil be flashing) 
it with be conected with isp mode, so feel free to flash it with the official tool or with kbtflash.py

**Comment by lactide** [comment]
That's really odd. The backlight poker II shouldn't be much different than the version without backlight.
Do you see any output in dmesg when you reconnect the usb cable?
Could you try to connect a debugger to check where it hangs?

**Comment by gompa** [comment]
when reconnecting there is no dmesg output, i dont have a debugger, ill order one and check

**Comment by gompa** [comment]
hmm after getting the debugger and rebuilding and flashing it seems to "just work "
so i guess the issue can be closed

**Comment by lactide** [comment]
Did you actually use the debugger or did you just reflash the board? I would have no idea if it worked just by flashing the application again. If you changed the bootloader with the modified binary from this repository then this might be a hint that the initialization code depends on it.
