### ISSUE TITLE
build error new master

### ISSUE THREAD

**Issue by gompa** [lactide/tmk_nuvoton#4]
thanks for updating the source ! 
i do have the following error trying to build : 
`Compiling hal_usb_lld.c
ChibiOS-Contrib/os/hal/ports/NUMICRO/NUC122/hal_usb_lld.c: In function 'NUMICRO_USB_IRQ_VECTOR':
ChibiOS-Contrib/os/hal/ports/NUMICRO/NUC122/hal_usb_lld.c:218:17: error: lvalue required as unary '&' operand
   serve_usb_irq(&USBD);
                 ^
ChibiOS-Contrib/os/hal/ports/NUMICRO/NUC122/hal_usb_lld.c: In function 'usb_lld_get_status_in':
ChibiOS-Contrib/os/hal/ports/NUMICRO/NUC122/hal_usb_lld.c:435:48: warning: unused parameter 'usbp' [-Wunused-parameter]
 usbepstatus_t usb_lld_get_status_in(USBDriver *usbp, usbep_t ep) {
                                                ^~~~
ChibiOS-Contrib/os/hal/ports/NUMICRO/NUC122/hal_usb_lld.c:435:62: warning: unused parameter 'ep' [-Wunused-parameter]
 usbepstatus_t usb_lld_get_status_in(USBDriver *usbp, usbep_t ep) {
                                                              ^~
make: *** [ChibiOS/os/common/startup/ARMCMx/compilers/GCC/rules.mk:223: build/obj/hal_usb_lld.o] Error 1
`

**Comment by lactide** [comment]
You need to update the submodules:
`git submodule update`

**Comment by gompa** [comment]
you are right ! thanks
